### ISSUE TITLE
Upgrade to Intl: 0.18.0

### ISSUE THREAD

**Issue by ronnross** [applanga/applanga_flutter#13]
When trying to update our flutter project we receive this error 

`Because applanga_flutter >=3.0.46 depends on intl ^0.17.0 and <my_app> depends on intl ^0.18.0, applanga_flutter >=3.0.46 is forbidden.
So, because <my_app> depends on applanga_flutter ^3.0.47, version solving failed.`

Could this project please upgrade the dependency on `Intl: 0.17.0`. to `Intl: 0.18.0`?

**Comment by leonardarnold** [comment]
Hi,

it's on the list, for now you could override the dependency with:
```
dependency_overrides:
  intl: ^0.18.1
```

**Comment by leonardarnold** [comment]
Is fixed in v 3.0.49
