### ISSUE TITLE
Need to have 3.0.47

### ISSUE THREAD

**Issue by thomtomdup** [applanga/applanga_flutter#15]
Hello.
Currently some of projects are not migrate to flutter 3.10 ( for stability investigations ) so the update of your package could not be possible to use.
You have delete 3.0.47 and i need it for Flutter 3.7.12.
I could not use it because from pub get it get automaticaly 3.0.48.
You use View that is not implemented in 3.7.12.
Is it possible to put 3.0.47 in your repo with the same tag ?
Thank you.
Regards

**Comment by leonardarnold** [comment]
How does your pubspec looks like? You still can use 3.0.47. I assume you use the caret syntax like: ^3.0.47. Remove the caret (^) and it should work. Thanks for pointing that out.
