### ISSUE TITLE
Android compilation  probleme.

### ISSUE THREAD

**Issue by thomtomdup** [applanga/applanga_flutter#16]
Hello.

I have a probleme when i want to build Android app.

This issue is appear : 
`The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.The following dependencies do not satisfy the required version:project ':applanga_flutter' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50`

Is it possible to solve it ?

Thank you !

**Comment by thomtomdup** [comment]
Hello.

I tried to update the Android project of this package and the new issue is for the SDK package com.applanga.android:Applanga:4.0.194.

**Comment by leonardarnold** [comment]
Hi, 
thanks for the report. I will need a little bit of time to look into it. What is the issue when upgrading the Android project?

**Comment by thomtomdup** [comment]
Hello.

I see that you have did some modifications.

Please update build.gradle of the project like this :

`
      group 'com.applanga.applanga_flutter'
      version '1.0-SNAPSHOT'
      
      buildscript {
          ext.kotlin_version = '1.7.10'
          repositories {
              google()
              mavenCentral()
          }
      
          dependencies {
              classpath 'com.android.tools.build:gradle:7.3.0'
              classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
          }
      }
      
      rootProject.allprojects {
          repositories {
              google()
              mavenCentral()
    	      maven { url 'https://maven.applanga.com/'}
          }
      }
      
      apply plugin: 'com.android.library'
      apply plugin: 'kotlin-android'
      
      android {
          compileSdkVersion 33
      
          sourceSets {
              main.java.srcDirs += 'src/main/kotlin'
          }
          defaultConfig {
              minSdkVersion 16
          }
      }
      
      dependencies {
          implementation "com.applanga.android:Applanga:4.0.195"
      
          implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
      }
`

**Comment by thomtomdup** [comment]
The gradle of you build.gradle file is a old gradle version and the best is to use the more latest version (same as kotlin).

Currently i use the last version of flutter and this is what is genererated by flutter for Android setting.

I used what you have pushed to master and i had some issues. 
By updated this build.gradle version all working good with the last version of Flutter and alos the min target version of Android (33).

**Comment by leonardarnold** [comment]
Ok cool!
The reason why I don't want to upgrade the Kotlin version to the highest one is that other users may still use older versions, which then can create issues for them. The newer Kotlin versions should obviously work with this package, so thanks for reporting it!

**Comment by leonardarnold** [comment]
Is fixed in v 3.0.49
