### ISSUE TITLE
example does not build with flutter 2.0 sdk

### ISSUE THREAD

**Issue by seankangsanofi** [applanga/applanga_flutter#2]
I am using flutter 2.0 SDK.  
The example does not successfully compile.
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/applanga_flutter-0.0.33/lib/applanga_flutter.dart:89:44: Error: Type argument 'Widget' doesn't conform to the bound 'StatefulWidget' of the type variable 'T' on 'State'.
 - 'StatefulWidget' is from 'package:flutter/src/widgets/framework.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try changing type arguments so that they conform to the bounds.
extension ApplangaStateWidgetEx<Widget> on State<Widget> {
                                           ^
../../../development/flutter/packages/flutter/lib/src/widgets/framework.dart:1052:22: Context: This is the type variable whose bound isn't conformed to.
abstract class State<T extends StatefulWidget> with Diagnosticable {
                     ^
../../../development/flutter/.pub-cache/hosted/pub.dartlang.org/applanga_flutter-0.0.33/lib/applanga_flutter.dart:90:8: Error: Type argument 'Widget' doesn't conform to the bound 'StatefulWidget' of the type variable 'T' on 'State'.
 - 'StatefulWidget' is from 'package:flutter/src/widgets/framework.dart' ('../../../development/flutter/packages/flutter/lib/src/widgets/framework.dart').
Try changing type arguments so that they conform to the bounds.
  void setScreenTag(BuildContext context, String tag) {
       ^
../../../development/flutter/packages/flutter/lib/src/widgets/framework.dart:1052:22: Context: This is the type variable whose bound isn't conformed to.
abstract class State<T extends StatefulWidget> with Diagnosticable {
                     ^

FAILURE: Build failed with an exception.

* Where:
Script '/Users/joe/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 991

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/joe/development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 3s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by applanga-rich** [comment]
Hi @seankangsanofi 

I'm looking at this now. I'll update here asap
