### ISSUE TITLE
Incompatible with the latest version of applanga's xcframework

### ISSUE THREAD

**Issue by david-all-win-software** [applanga/applanga_flutter#9]
When trying to compile on iPhone the dependency breaks the compilation because the import does not find Applanga.h
This occurs only from the latest versions of the Applanga pod.

How to replicate, from the example project https://github.com/applanga/applanga_flutter/tree/master/example:
1. Remove `ios/Podfile.lock` so that it can obtain a version of Applanga greater than 2.0.158
2. Try running on an ios simulator with `flutter run`
3. This will fail to compile because it can't find Applanga.h

**Comment by leonardarnold** [comment]
Hi David,

I can't reproduce your issue.
What I've tried:
- `rm example/ios/Podfile.lock`
- `flutter clean`
- `flutter run`

Please try it like above with `flutter clean` as well.
If it still persists post here your `flutter doctor` output.

**Comment by leonardarnold** [comment]
@david-all-win-software  Thanks for the details. I could reproduce it. `"Applanga/Applanga.h"` is the solution indeed. I am wondering why this pops up now. We will deploy it the fix soon. We also will bump up all the dependency versions of `pubspec.yaml`.

**Comment by leonardarnold** [comment]
This issue should be fixed in version 3.0.45 @david-all-win-software

**Comment by david-all-win-software** [comment]
@leonardarnold Thank you very much. 
Although I see another incompatibility when executing `flutter pub add applanga_flutter:3.0.45` from my enviroment. it seems with analyzer

```
Because every version of flutter from sdk depends on collection 1.16.0 and analyzer >=5.3.1 depends on collection ^1.17.0, flutter from sdk is incompatible with analyzer >=5.3.1.
And because applanga_flutter >=3.0.45 depends on analyzer ^5.3.1, flutter from sdk is incompatible with applanga_flutter >=3.0.45.
So, because betterhodl_flutter depends on both flutter from sdk and applanga_flutter 3.0.45, version solving failed.
pub finished with exit code 65
```

**Comment by leonardarnold** [comment]
can you please make another issue for it? Thanks!
